-- CREATE A TABLE
DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
);


--CREATE
INSERT INTO TB_HEROES
(NOME, PODER) 
    VALUES 
    ('FLASH', 'SPEED'),
    ('BATMAN', 'MONEY');


--BASIC READ
SELECT * FROM TB_HEROES;


--FILTER READ
SELECT * FROM TB_HEROES WHERE ID = '2';


--UPDATE 
UPDATE TB_HEROES SET NOME='GOKU' , PODER= 'CAMEHAMEHA' WHERE ID=2;


--DELETE
DELETE FROM TB_HEROES WHERE ID=5;